language: C

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks make

script: lua test_bufflib.lua

notifications:
  recipients:
    - Choonster.2010@gmail.com
  email:
    on_success: change
    on_failure: always