language: c

env:
  global:
    - LUA_CPATH="/home/travis/build/Choonster/lua_bufflib/?.so"
    - LUA_LIBDIR=/usr/lib/x86_64-linux-gnu/
  matrix:
    - "LUA=lua5.1 LUA_INCDIR=/usr/include/lua5.1 LUA_LIB=lua5.1"
    - "LUA=lua5.2 LUA_INCDIR=/usr/include/lua5.2 LUA_LIB=lua5.2"
    - "LUA=luajit LUA_INCDIR=/usr/include/luajit-2.0 LUA_LIB=luajit-5.1"

branches:
  only:
    - master

compiler:
  - "clang"
  - "gcc"

before_install:
  - "sudo add-apt-repository ppa:mwild1/ppa -y"
  - "sudo apt-get update -y"

install:
  - "sudo apt-get install luajit -y"
  - "sudo apt-get install libluajit-5.1-dev -y"
  - "sudo apt-get install lua5.1"
  - "sudo apt-get install liblua5.1-dev"
  - "sudo apt-get install lua5.2"
  - "sudo apt-get install liblua5.2-dev"

script:
  - "gcc -ansi -O2 -fPIC -I $LUA_INCDIR -L $LUA_LIBDIR -l$LUA_LIB -c lua_bufflib.c -o bufflib.o"
  - "gcc -shared -o bufflib.so bufflib.o"
  - "echo $PWD"
  - "echo $CC"
  - cat cc
  - "ls bufflib.so"
  - "$LUA -v test_bufflib.lua"

notifications:
  email:
    on_failure: always
    on_success: change
